[package]
name = "cg-bundler"
version = "0.1.0"
authors = ["CG Bundler Contributors"]
description = "A Rust code compression tool that minifies Rust codebases into single-line format"
documentation = "https://docs.rs/cg-bundler"
homepage = "https://github.com/MathieuSoysal/cg-bundler"
repository = "https://github.com/MathieuSoysal/cg-bundler"
keywords = ["minify", "compress", "single-line", "rust", "cli"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
license = "MIT"
edition = "2021"

[[bin]]
name = "cg-bundler"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
syn = { version = "2.0", features = ["full", "extra-traits", "visit-mut", "parsing"] }
proc-macro2 = "1.0"
quote = "1.0"
anyhow = "1.0"
thiserror = "1.0"
walkdir = "2.3"
colored = "2.0"
cargo_metadata = "0.18"
prettyplease = "0.2"

[dev-dependencies]
tempfile = "3.0"
assert_cmd = "2.0"
predicates = "3.0"
proptest = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }
