# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[licenses]
# List of licenses that are allowed
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "MPL-2.0",
    "CC0-1.0",
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    #"RUSTSEC-0000-0000",
]

[sources]
# Lint level for what to happen when a crate registry that is not
# in the allow list is encountered
unknown-registry = "warn"
# List of URLs for allowed crate registries. Defaults to the crates.io index
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
