blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/MathieuSoysal/cg-bundler/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://docs.rs/cg-bundler
    about: Check out the full documentation and API reference
  - name: 🔒 Security Issue
    url: https://github.com/MathieuSoysal/cg-bundler/security/advisories/new
    about: Report security vulnerabilities privately (do not create public issues)
