name: Dependency Update

permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Prevent multiple dependency updates from running simultaneously
concurrency:
  group: dependency-update
  cancel-in-progress: true

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache cargo tools to avoid reinstalling them every time
      - name: Cache cargo tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-audit
            ~/.cargo/bin/cargo-deny
            ~/.cargo/bin/cargo-edit
            ~/.cargo/bin/cargo-llvm-cov
          key: ${{ runner.os }}-cargo-tools-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-tools-

      - name: Install cargo tools
        run: |
          if ! command -v cargo-edit &> /dev/null; then
            cargo install cargo-edit
          fi

      # Cache dependencies to speed up builds
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Update dependencies
        id: update
        run: |
          # Update Cargo.toml dependencies to latest compatible versions
          cargo update
          
          # Check if there are any changes
          if git diff --quiet Cargo.lock; then
            echo "No dependency updates available"
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "Dependencies updated"
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Run tests after update
        if: steps.update.outputs.has_updates == 'true'
        run: |
          cargo test --verbose
          cargo build --release

      - name: Create Pull Request
        if: steps.update.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: automated dependency update"
          body: |
            ## Automated Dependency Update
            
            This PR contains automated dependency updates generated by the dependency update workflow.
            
            ### Changes
            - Updated `Cargo.lock` with latest compatible dependency versions
            
            ### Testing
            - ✅ All tests pass
            - ✅ Release build succeeds
            
            ### Review Checklist
            - [ ] Review updated dependencies for any breaking changes
            - [ ] Verify all tests still pass
            - [ ] Check for any security advisories for updated packages
            
            This PR was automatically created by the dependency update workflow.
          branch: automated-dependency-update
          delete-branch: true
          draft: false
