name: Security Audit

permissions:
  contents: read
  security-events: write

on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  push:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
  workflow_dispatch:

# Prevent multiple security audits from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install security tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-deny

      # Cache dependencies to speed up builds
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-security-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-security-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-security-
            ${{ runner.os }}-cargo-

      - name: Run cargo audit
        run: |
          echo "Running cargo audit..."
          cargo audit --json > audit-report.json 2>&1 || echo "::warning::Audit found vulnerabilities"
          cargo audit 2>&1 | tee audit-report.txt || echo "::warning::Audit found vulnerabilities"

      - name: Run cargo deny
        run: |
          echo "Running cargo deny check..."
          cargo deny check --format json > deny-report.json 2>&1 || echo "::warning::Deny check found issues"
          cargo deny check 2>&1 | tee deny-report.txt || echo "::warning::Deny check found issues"

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.run_number }}
          path: |
            audit-report.txt
            audit-report.json
            deny-report.txt
            deny-report.json
          retention-days: 30

      - name: Create security summary
        if: always()
        run: |
          echo "## Security Audit Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Cargo Audit Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -20 audit-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "### Cargo Deny Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -20 deny-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
