name: Security Audit

permissions:
  contents: read
  security-events: write

on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Prevent multiple security audits from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache cargo tools to avoid reinstalling them every time
      - name: Cache cargo tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-audit
            ~/.cargo/bin/cargo-deny
            ~/.cargo/bin/cargo-edit
            ~/.cargo/bin/cargo-llvm-cov
          key: ${{ runner.os }}-cargo-tools-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-tools-

      - name: Install cargo tools
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi
          if ! command -v cargo-deny &> /dev/null; then
            cargo install cargo-deny
          fi

      # Cache dependencies to speed up builds
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run cargo audit
        run: |
          echo "Running cargo audit..."
          cargo audit --json > audit-report.json 2>&1 || echo "Audit found issues"
          cargo audit > audit-report.txt 2>&1 || echo "Audit found issues"

      - name: Run cargo deny
        run: |
          echo "Running cargo deny check..."
          cargo deny check --format json > deny-report.json 2>&1 || echo "Deny check found issues"
          cargo deny check > deny-report.txt 2>&1 || echo "Deny check found issues"

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.run_number }}
          path: |
            audit-report.txt
            audit-report.json
            deny-report.txt
            deny-report.json
          retention-days: 30
